### PR TITLE
wip merge

### LINKED ISSUE #60: CI tests can only ever pass on the same day new data is pushed
https://github.com/pelias/placeholder/blob/master/.travis.yml#L14-L18 shows that Travis downloads data with the current date in the URL. However, we don't, and probably don't want to, push new data to S3 every day. This means tests will fail on most days.

Ideally the tests are separated into unit/functional tests that have their own mock data and can run without downloading any data.

### PR DESCRIPTION
**Pull request by missinglink**
in anticipation of a larger refactoring PR, the code in this PR can be merged ahead of the rest in order to make reviews easier:

- split test suites into 'unit' and 'integration' - this divides the tests which are purely testing js functions from those testing interactions with the database(s).
- add a script which downloads and extracts wof bundles in one step - for convenience.
- minor UI performance tweaks to the demo app
- enable cluster module for muticore http, add cache control headers (enables browser caching).

I also added a fix for https://github.com/pelias/placeholder/issues/60 so that the latest production data is used when a daily archive is not available.

resolves https://github.com/pelias/placeholder/issues/60

### CODE REVIEW

File: server/http.js [hunk 1]
```diff
@@ -35,12 +37,19 @@ app.use(log());
 
 // init placeholder
 console.error( 'loading data' );
-var ph = new Placeholder();
+var ph = new Placeholder({ readonly: true });
```
Comment (missinglink) [inline server/http.js:62]: this setting currently does nothing but I left it in because, although it doesn't actually do anything it's valid to create `ph` as read-only in server mode.

in the subsequent PRs this setting will cause the underlying databases to be opened in read-only mode.

File: server/http.js [hunk 2]
```diff
@@ -1,14 +1,38 @@
...
+const os = require('os');
+const morgan = require('morgan');
+const express = require('express');
+const cluster = require('cluster');
+const through = require('through2');
 const _ = require('lodash');
 
-// optionally override port using env var
+const Placeholder = require('../Placeholder.js');
+const logger = require('pelias-logger').get('interpolation');
```
Comment (orangejulius) [inline server/http.js]: this should be `placeholder`, not `interpolation`, right?

File: server/http.js [hunk 3]
```diff
@@ -1,14 +1,38 @@
...
+
+// select the amount of cpus we will use
+const envCpus = parseInt( process.env.CPUS, 10 );
```
Comment (orangejulius) [inline server/http.js]: I think I remember reading somewhere that Node.js defaults to base 10 for parseInt, and I know that as of ES5, the problem with leading zeros causing the number to be interpreted as octal is now gone. Specifying the radix is still best practice on the web, but I wonder if we still need to do it. Any ideas?

**Comment by orangejulius** [comment]
Fixing the Travis tests and splitting up the tests is great! I think there's one minor typo, otherwise it looks good.

File: server/http.js (hunk 3 above)
Comment (missinglink) [reply server/http.js]: The mozilla docs are availabe online for you to have a look at.

> Always specify this parameter to eliminate reader confusion and to guarantee predictable behavior.

File: server/http.js (hunk 1 above)
Comment (missinglink) [reply server/http.js]: good catch, this was introduced in https://github.com/pelias/placeholder/commit/8d83744e69dda00673412d2890f32cd5446899fb, I will add another commit to fix it in this PR

File: server/http.js (hunk 2 above)
Comment (missinglink) [reply server/http.js]: good catch, this was introduced in https://github.com/pelias/placeholder/commit/8d83744e69dda00673412d2890f32cd5446899fb, I will add another commit to fix it in this PR

**Review by dianashk — APPROVED** [review]
